version: '3.6'
services:
  app:
    build: .
    volumes:
      - '.:/app'
    links:
      - database
    depends_on:
      - database
      - mailhog
  api:
    restart: always
    build: ./api
    links:
      - database
    volumes:
      - './api:/app'
    networks:
      - api_bridge
  database:
    image: 'mariadb'
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - api_bridge
  nginx:
    image: 'nginx'
    links:
      - app
    volumes:
      - './:/app'
      - './humanaid_bo.conf:/etc/nginx/conf.d/default.conf'
      - './logs/nginx/:/var/log/nginx'
  adminer:
    image: 'adminer'
    environment:
      - ADMINER_DEFAULT_SERVER=database
      - ADMINER_DESIGN=brade
  mailhog:
    image: 'mailhog/mailhog'
networks:
  api_bridge:
    driver: bridge