version: '3.6'

services:
  php:
    ports:
      - '9000:9000'
  nginx:
    ports:
      - '80:80'
  adminer:
    ports:
      - '8081:8080'
  database:
    ports:
      - '3306:3306'
  mailhog:
    ports:
      - '8025:8025'
      - '1025:1025'